apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saaspodinfo-git
  namespace: argocd
spec:
  project: default  
  destination:
    namespace: cfg  #update namespace name if you wish
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/m3rryqold/cfghelm.git'  #replace with your username
    path: gcp
    targetRevision: HEAD
    helm:
      valueFiles:
      - /dev/stdin
      values: |
        {{- $values := `gsutil cat gs://bucket-zero1/cfghelm_gcp_stg-values.yaml --service-account=/secrets/key.json` -}}
        {{- $values }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  volumes:
    - name: cfg-key
      secret:
        secretName: cfg-secret
        defaultMode: 420
