apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saaspodinfo-git
  namespace: argocd
spec:
  project: default  
  destination:
    namespace: cfg  #update namespace name if you wish
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/m3rryqold/cfghelm.git'  #replace with your username
    path: gcp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  podSpecPatch: |-
    - op: add
      path: /spec/template/spec/containers/-
      value:
        name: gcs-downloader
        image: google/cloud-sdk:latest
        command:
          - "/bin/bash"
          - "-c"
          - |
            gcloud auth activate-service-account --key-file=/secrets/key.json
            gsutil cp gs://bucket-zero1/cfghelm_gcp_stg-values.yaml /tmp/values.yaml
        volumeMounts:
          - name: cfg-key
            mountPath: /secrets
            readOnly: true
          - name: values-file
            mountPath: /tmp/values.yaml
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/key.json
  volumes:
    - name: cfg-key
      secret:
        secretName: cfg-secret
        defaultMode: 420
    - name: values-file
      emptyDir: {}
