apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saaspodinfo-git
  namespace: argocd
spec:
  project: default  
  destination:
    namespace: cfg  #update namespace name if you wish
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/m3rryqold/cfghelm.git'  #replace with your username
    path: gcp
    targetRevision: HEAD
    helm:
      valueFiles:
      - command: ["/bin/sh", "-c", "gcloud auth activate-service-account --key-file /var/secrets/cfg-secret/key.json && gsutil cat gs://bucket-zero1/cfghelm_gcp_stg-values.yaml"]
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  volumes:
    - name: cfg-secret
      secret:
        secretName: cfg-secret
  volumeMounts:
    - name: cfg-secret
      mountPath: /var/secrets/cfg-secret
      subPath: key.json
