apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfg-secret
  namespace: cfg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: values-file
  namespace: cfg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
