apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80  # Expose service on port 80
      targetPort: 8080  # Route traffic to port 8080 on the pods
  type: LoadBalancer
